### PR TITLE
Remove unnecessary validation

### PR DESCRIPTION
**Pull request by nabroleonx**

### CODE REVIEW

**Comment by nabroleonx** [comment]
The npm package needs to be updated accordingly. Are you going to create a package yourself or continue with the one **FuadHy** did?

**Comment by isrugeek** [comment]
@nabroleonx Since this is @fuadhy's work, we will stick with his package. If he doesn't keep it up to date, we will be forced to create one.

**Comment by FuadHy** [comment]
Hello, the reason I didn't update the npm package is that it didn't get any bug fixes or other updates, the changes were syntactical, so just changing the module version without significant updates may be unnecessary.

**Comment by FuadHy** [comment]
@isrugeek, @nabroleonx.  the last commit in this repo has issues I think,  the required fields are necessary, according to the docs https://developer.chapa.co/docs/accept-payments/

**Comment by isrugeek** [comment]
Hi @FuadHy 

Yes, I meant to close the PR, not accept it. I am going to do a knock.

**Comment by FuadHy** [comment]
Oops (:

**Comment by nabroleonx** [comment]
@isrugeek @FuadHy You guys are right, those fields are required according to the [docs](https://developer.chapa.co/docs/accept-payments/). 

That was why when @FuadHy did the error checking for empty fields first and I added the error array to make it return a JSON object for easy display in the frontend. However, I found out the API returns a JSON object so doing this validation is redundant That was why I removed it. 

image

This is what the default error validation response looks like👆🏾. Check it and you will see what I am talking about.

**Comment by FuadHy** [comment]
@nabroleonx Adding validations to the SDK increases speed when catching errors. Instead of waiting the API to validate the data.

**Comment by nabroleonx** [comment]
@FuadHy Yes indeed, if that was the motive great. I just thought you forgot that the API actually validates it. :)

**Pull request merged**
